# Generated by Django 4.2 on 2023-04-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spouse_name',
        ),
    ]
